### ISSUE TITLE
codyco-superbuild fails without iDynTree

### ISSUE THREAD

**Issue by bmagyar** [vvv-school/vvv-school.github.io#2]
I've got this to work before but forgot how I did it :) 
This is missing from the manual installation.

Getting the stuff from `https://github.com/robotology/idyntree-superbuild` is ok but which parameters should be switched on for compilation? Without setting specific builds there's nothing to `make`.

**Comment by pattacini** [comment]
Thanks @bmagyar for pointing this out.
@francesco-romano could you deal with that?

**Comment by bmagyar** [comment]
I'm happy to test the solution before it's added to the description!

**Comment by traversaro** [comment]
Hi @bmagyar , 
 `codyco-superbuild` should autonomously download and build `idyntree` without any need to compile `idyntree` separately. 

Can you paste the error that you got? Thanks!

**Comment by bmagyar** [comment]
Hiya,

`/home/bence/robot-code/codyco-superbuild/libraries/codycoCommons/src/ModelParsing.cpp:21:48: fatal error: iCub/iDynTree/TorqueEstimationTree.h: No such file or directory`

```
~/robot-code/codyco-superbuild$ find . -iname *TorqueEstimation*
```
returns nothing at all

**Comment by traversaro** [comment]
You have another iDynTree in your system? 

It seems that the superbuild is not downloading and using the internal iDynTree, but it is using an external one  compiled without with the `IDYNTREE_USES_ICUB` flag turned to OFF (that is indeed the default `idyntree-superbuild` setting). 

This is a bug in the codyco-superbuild build system, that should check that the system iDynTree is compiled with ICUB support before deciding it is ok to use it. : )

As a temporary workaround, you can set the `USE_SYSTEM_iDynTree` flag in codyco-superbuild to force the use of a `codyco-superbuild` specific version of iDynTree (see https://robotology.github.io/ycm/gh-pages/master/manual/ycm-superbuild.7.html#ycm-superbuild-manual-for-developers ).

**Comment by bmagyar** [comment]
You are right, I had a folder of it elsewhere but that one was never actually compiled here nor any path was set up to it, I copied that over and was in a catkin workspace.
After I removed the folder it is downloading it although it'd be handy if it'd told me anything about the error.

Thanks for the help, it compiled!
