### ISSUE TITLE
Installing himrep doesn't work without CUDA toolkit

### ISSUE THREAD

**Issue by bmagyar** [vvv-school/vvv-school.github.io#4]
Or to put it differently: should I try getting nvidia drivers & cuda or can I survive without them by disabling it in the cmake?

It should figure this out from the Caffe installation but it seems to fail on it.

For completeness:
```
bence@blackbrick:~/robot-code/himrep/build$ cmake ..
-- Using iCub from install
-- Libraries are placed in /home/bence/robot-code/himrep/build/lib
-- Executables are placed in /home/bence/robot-code/himrep/build/bin
-- Searching LIBSVMLIN.
-- LIBSVMLIN_FOUND - YES.
-- Searching LIBSVM.
-- Folder "" not found.
-- LIBSVM_FOUND - NO.
-- SIFTGPU not found => sparseCoder will not be built
CMake Warning (dev) at /home/bence/robot-code/caffe/build/CaffeConfig.cmake:22 (if):
  given arguments:

    "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
Call Stack (most recent call first):
  modules/CMakeLists.txt:8 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Caffe is found => caffeCoder will be compiled
CMake Error at /usr/share/cmake-3.5/Modules/FindCUDA.cmake:617 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  modules/caffeCoder/src/CMakeLists.txt:61 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/bence/robot-code/himrep/build/CMakeFiles/CMakeOutput.log".

```

**Comment by vtikha** [comment]
Hi @bmagyar, I made a clean installation of `himrep` repo and it all went ok. I confirm that the installation does figure out from caffe the necessity of building/linking with cuda. But I actually just noticed that the instructions for building `caffe` we put online, miss to say to turn the flag `CPU_ONLY` to `ON` which should be used if no CUDA is required. How is your system set-up?. Please use the `CPU_ONLY ON` flag in `Caffe` and rebuild both `Caffe` and `himrep` and let me know. I will update the documentation accordingly.

**Comment by bmagyar** [comment]
Great! I was about to open a PR but I see you added it already. Thanks!
I'm all set, the final simulation test works.

**Comment by vtikha** [comment]
Excellent 👍
