### ISSUE TITLE
Can't upload Sentis' slides on vvv18

### ISSUE THREAD

**Issue by lornat75** [vvv-school/vvv-school.github.io#6]
Should we ask for large filesystem support for our organization?

**Comment by vtikha** [comment]
@lornat75, how big is the file?

**Comment by pattacini** [comment]
I'd rather go for reducing the PDF size, which I often do.

**Comment by lornat75** [comment]
50MB, but, isn't it a feature that we can come handy in the future anyway?

**Comment by pattacini** [comment]
Also, consider that uploading a file via UI is limited in terms of size wrt the usual push.

**Comment by pattacini** [comment]
50 MB is not problematic anyway.
However, I would still reduce the size. I've got the feature to do that from within Acrobat.

**Comment by pattacini** [comment]
Done!

**Comment by lornat75** [comment]
it was decided that the LFS is an overkill, because git interface allows files as large as 100Mb, and @pattacini can shrink slides on demand :)
