### ISSUE TITLE
Update hands-on to use YARP >= 3.0.0

### ISSUE THREAD

**Issue by pattacini** [vvv-school/vvv-school.github.io#7]
We need to update the repositories listed below to use YARP >= 3.0.0. I've already handled some of them (those ticked in), whose latest commits can give you easy hints to follow.

@arrenglover @Nicogene @traversaro @barbalberto @GiuliaP it might be convenient to address the update before VVV19 given that the courses and the related hands-on are generically useful for YARP beginners.

In particular, **YARP tutorials** will be used to train our new PhD students.   

- [x] assignment_git
- [x] tutorial_joint-interface
- [x] tutorial_cartesian-interface
- [x] tutorial_gaze-interface
- [x] assignment_make-it-roll
- [x] solution_make-it-roll
- [x] assignment_grasp-it
- [x] solution_grasp-it
- [x] tutorial_inverse-kinematics
- [x] assignment_inverse-kinematics
- [x] solution_inverse-kinematics
- [x] assignment_collatz-conjecture
- [x] solution_collatz-conjecture
- [x] assignment_motor-control
- [x] solution_motor-control
- [x] tutorial_find-wally
- [x] tutorial_yarp-opencv
- [x] assignment_closest-blob
- [x] solution_closest-blob
- [x] assignment_control-pid
- [x] solution_control-pid
- [x] assignment_yarp-find-rgb
- [x] solution_yarp-find-rgb
- [x] assignment_solve-maze
- [x] assignment_producer-consumer
- [x] solution_producer-consumer
- [x] tutorial_yarp-basics
- [x] tutorial_yarp-producer-consumer
- [x] tutorial_yarp-ports
- [x] tutorial_yarp-rpc
- [x] tutorial_RFModule
- [x] tutorial_RFModule-simple
- [x] tutorial_yarp-multithreading
- [x] tutorial_yarp-idl
- [x] tutorial_yarpmanager
- [x] tutorial_impedance-control
- [x] assignment_codec
- [x] solution_codec
- [x] assignment_computed-torque
- [x] solution_computed-torque
- [x] tutorial_impedance-control-simulink
- [x] assignment_computed-torque-simulink
- [x] solution_computed-torque-simulink
- [x] tutorial_event-driven-flow
- [x] tutorial_event-handling
- [x] tutorial_event-driven-framework
- [x] assignment_event-spiking-model
- [x] solution_event-spiking-model
- [x] assignment_event-orientation-filter
- [x] solution_event-orientation-filter
- [x] assignment_event-saliency-map
- [x] solution_event-saliency-map
- [x] assignment_event-saccadic-suppression
- [x] solution_event-saccadic-suppression
- [x] assignment_event-spiking-attention
- [x] solution_event-spiking-attention
- [x] tutorial_dl-tuning
- [x] tutorial_dl-deployment
- [x] assignment_dl-tuning
- [x] solution_dl-tuning

**Comment by traversaro** [comment]
In progress. General comment: if you update a repo to work **only** with YARP >= 3.0, always add the `find_package(YARP 3.0 REQUIRED)` comment, so if some user try to compile it with an old YARP he will get a clear error message.

**Comment by traversaro** [comment]
I updated: 
* [`tutorial_impedance-control`](https://github.com/vvv-school/tutorial_impedance-control/commit/b84b2394f80454972ce2021aba571a9957ea6a1c) 
* [`assignment_computed-torque`](https://github.com/vvv-school/assignment_computed-torque/commit/3afe5eaa0a524118676c6fc601c3b83191935f05)
* [`solution_computed-torque`](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

@diegoferigo can you take care of the WB-Toolbox tutorials/assignments? I think they need to be updated from WB-Toolbox 3 to 4. For the smoke test I think you can copy most of what done in https://github.com/vvv-school/assignment_computed-torque/commit/3afe5eaa0a524118676c6fc601c3b83191935f05 .

**Comment by traversaro** [comment]
> given that the courses and the related hands-on are generically useful for YARP beginners

Indeed, once we completed the update I think we should  reference all this tutorials from the YARP main documentation at http://yarp.it/ . This  tutorials are probably one of the best educational material related to YARP, but people landing on the YARP homepage have no idea they exist at all.

**Comment by pattacini** [comment]
>In progress. General comment: if you update a repo to work **only** with YARP >= 3.0, always add the `find_package(YARP 3.0 REQUIRED)` comment, so if some user try to compile it with an old YARP he will get a clear error message.

good point @traversaro; I'm going to fix this in the repos I've already touched.

**Comment by Nicogene** [comment]
I'll update the yarp tutorials!

**Comment by Nicogene** [comment]
+1000 for @traversaro 's proposal

**Comment by arrenglover** [comment]
no problems - I'll get the event-driven tutorials done ASAP

**Comment by pattacini** [comment]
Don't forget to tick those repositories above once you will have applied the update!

**Comment by arrenglover** [comment]
There are some of the event-driven repositories which I made for the first winter school but are not used anymore. I don't think it's worthwhile spending the time to keep them up-to-date. Should they be archived/moved/deleted?

**Comment by pattacini** [comment]
Hi @arrenglover thanks for dealing with this!

If those repositories can be considered still operative, that is they contain pieces of code that can support teaching, then I'd say it is still worth updating them, also given that the update is quite easy.

By contrast, if those repositories are somehow superseded by other more recent repos, then I would do the following:
- **Fill in the `README.md`** file with a disclaimer saying that the repo is replaced by some more recent code (pointer to the newest code goes here).
- Mark the repo as **archived** (don't forget to archive `solution_*` counterparts too).

**Comment by pattacini** [comment]
`[assignment|solution]_codec` done.

**Comment by pattacini** [comment]
@arrenglover [`tutorial_event-handling`](https://github.com/vvv-school/tutorial_event-handling) has a `smoke-test` that needs to be updated as well.

**Comment by arrenglover** [comment]
> @arrenglover tutorial_event-handling has a smoke-test that needs to be updated as well.

Thanks for checking. Done.

**Comment by pattacini** [comment]
Thanks @arrenglover 

I've just added a couple of comments within your commit updating the smoke-test.

**Comment by pattacini** [comment]
Great job @arrenglover and @Nicogene thanks a lot 🥇 

@diegoferigo and @GiuliaP it's your turn, at your convenience.

**Comment by pattacini** [comment]
Update completed.
